2020-12-27 20:10:10,735 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2020-12-27 20:10:10,735 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python39\lib\site-packages\instabot\bot\bot.py
2020-12-27 20:10:19,848 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-12-27 20:10:20,577 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-12-27 20:10:21,060 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-12-27 20:10:21,557 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-12-27 20:10:21,895 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-12-27 20:10:24,390 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-12-27 20:10:24,390 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "The password you entered is incorrect. Please try again.", "invalid_credentials": true, "error_title": "Incorrect password for vv", "buttons": [{"title": "Try Again", "action": "dismiss"}], "status": "fail", "error_type": "bad_password"}'
2020-12-27 20:10:24,390 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2020-12-27 20:10:24,391 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: The password you entered is incorrect. Please try again.
2020-12-27 20:10:24,391 - instabot version: 0.117.0 (api) - INFO - Error type: bad_password
2020-12-27 20:10:24,392 - instabot version: 0.117.0 (api) - ERROR - Failed to login go to instagram and change your password
2020-12-27 20:10:24,403 - instabot version: 0.117.0 (api) - INFO - Username or password is incorrect.
